package UI;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import config.Config;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Monty
 */
public class MainUI extends javax.swing.JFrame {
    
    List<Data> UserList = new ArrayList<Data>();
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pat = null;

    public MainUI() {
        initComponents();
        con = Config.connectDB();
        fetchitemDetailsAS();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jSlider1 = new javax.swing.JSlider();
        Menu_bar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Btn_checkstock = new javax.swing.JButton();
        Btn_editstock = new javax.swing.JButton();
        Btn_addstock = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        Add_stock = new javax.swing.JPanel();
        Title_addstrock = new javax.swing.JLabel();
        LabelAS_Name = new javax.swing.JLabel();
        FieldAS_Name = new javax.swing.JTextField();
        LabelAS_Price = new javax.swing.JLabel();
        FieldAS_Price = new javax.swing.JTextField();
        LabelAS_Stock = new javax.swing.JLabel();
        FieldAS_Stock = new javax.swing.JTextField();
        Btn_Add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAS = new javax.swing.JTable();
        jComboBoxAs = new javax.swing.JComboBox<>();
        LabelAS_Type = new javax.swing.JLabel();
        Check_stock = new javax.swing.JPanel();
        Title_checkstock = new javax.swing.JLabel();
        LabelCS_Name = new javax.swing.JLabel();
        LabelCS_ID = new javax.swing.JLabel();
        FieldCS_ID = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCS = new javax.swing.JTable();
        LabelCS_Stock = new javax.swing.JLabel();
        FieldCS_Stock = new javax.swing.JTextField();
        Btn_re = new javax.swing.JButton();
        FieldCS_Name = new javax.swing.JTextField();
        Edit_stock = new javax.swing.JPanel();
        Title_editstock = new javax.swing.JLabel();
        LabelES_Name = new javax.swing.JLabel();
        FieldES_Name = new javax.swing.JTextField();
        LabelES_Price = new javax.swing.JLabel();
        FieldES_Price = new javax.swing.JTextField();
        LabelES_Stock = new javax.swing.JLabel();
        FieldES_Stock = new javax.swing.JTextField();
        BtnES_Update = new javax.swing.JButton();
        BtnES_Delete = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableES = new javax.swing.JTable();
        jComboBoxEs = new javax.swing.JComboBox<>();
        LabelES_Type = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu_bar.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Stock");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Management");

        Btn_checkstock.setBackground(new java.awt.Color(255, 255, 255));
        Btn_checkstock.setText("Check Stock");
        Btn_checkstock.setAlignmentY(10.0F);
        Btn_checkstock.setIconTextGap(10);
        Btn_checkstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_checkstockMouseClicked(evt);
            }
        });
        Btn_checkstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_checkstockActionPerformed(evt);
            }
        });

        Btn_editstock.setBackground(new java.awt.Color(255, 255, 255));
        Btn_editstock.setText("Edit Stock");
        Btn_editstock.setIconTextGap(10);
        Btn_editstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_editstockMouseClicked(evt);
            }
        });
        Btn_editstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_editstockActionPerformed(evt);
            }
        });

        Btn_addstock.setBackground(new java.awt.Color(255, 255, 255));
        Btn_addstock.setText("Add Stock");
        Btn_addstock.setIconTextGap(10);
        Btn_addstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_addstockMouseClicked(evt);
            }
        });
        Btn_addstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_addstockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_barLayout = new javax.swing.GroupLayout(Menu_bar);
        Menu_bar.setLayout(Menu_barLayout);
        Menu_barLayout.setHorizontalGroup(
            Menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_barLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_checkstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_editstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_addstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Menu_barLayout.setVerticalGroup(
            Menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_barLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Btn_checkstock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_addstock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_editstock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Add_stock.setBackground(new java.awt.Color(204, 204, 204));

        Title_addstrock.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Title_addstrock.setText("Add Stock");

        LabelAS_Name.setText("Item Name");

        LabelAS_Price.setText("Price [1=Unit]");

        LabelAS_Stock.setText("Stock [1=Unit]");

        Btn_Add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Btn_Add.setText("Add");
        Btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_AddMouseClicked(evt);
            }
        });

        jTableAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Name", "Date", "Price[Unit]", "Stock[1=Unit]"
            }
        ));
        jTableAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableASMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAS);

        jComboBoxAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronics", "Food", "Beauty", "Fashion", "Health", "Household", "Kitchen", "Sports" }));
        jComboBoxAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAsActionPerformed(evt);
            }
        });

        LabelAS_Type.setText("Type");

        javax.swing.GroupLayout Add_stockLayout = new javax.swing.GroupLayout(Add_stock);
        Add_stock.setLayout(Add_stockLayout);
        Add_stockLayout.setHorizontalGroup(
            Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_stockLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(Add_stockLayout.createSequentialGroup()
                        .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Add_stockLayout.createSequentialGroup()
                                .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldAS_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelAS_Name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldAS_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelAS_Price))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldAS_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelAS_Stock))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAS_Type)
                                    .addComponent(jComboBoxAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Title_addstrock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        Add_stockLayout.setVerticalGroup(
            Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_stockLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title_addstrock)
                .addGap(18, 18, 18)
                .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Add_stockLayout.createSequentialGroup()
                        .addComponent(LabelAS_Type)
                        .addGap(29, 29, 29))
                    .addGroup(Add_stockLayout.createSequentialGroup()
                        .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAS_Price, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelAS_Stock, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelAS_Name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Add_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldAS_Name)
                            .addComponent(jComboBoxAs)
                            .addComponent(FieldAS_Stock)
                            .addComponent(FieldAS_Price))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        Check_stock.setBackground(new java.awt.Color(204, 204, 204));

        Title_checkstock.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Title_checkstock.setText("Check Stock");

        LabelCS_Name.setText("Item Name");

        LabelCS_ID.setText("Item ID");

        FieldCS_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldCS_IDKeyReleased(evt);
            }
        });

        jTableCS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Name", "Date", "Price[Unit]", "Stock[1=Unit]"
            }
        ));
        jTableCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCSMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableCS);

        LabelCS_Stock.setText("Stock");

        FieldCS_Stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldCS_StockKeyReleased(evt);
            }
        });

        Btn_re.setText("Refresh Table");
        Btn_re.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_reMouseClicked(evt);
            }
        });

        FieldCS_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldCS_NameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout Check_stockLayout = new javax.swing.GroupLayout(Check_stock);
        Check_stock.setLayout(Check_stockLayout);
        Check_stockLayout.setHorizontalGroup(
            Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Check_stockLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Check_stockLayout.createSequentialGroup()
                        .addComponent(Title_checkstock)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Check_stockLayout.createSequentialGroup()
                        .addGroup(Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Check_stockLayout.createSequentialGroup()
                                .addGroup(Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCS_Name)
                                    .addComponent(FieldCS_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCS_ID)
                                    .addComponent(FieldCS_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Check_stockLayout.createSequentialGroup()
                                        .addComponent(LabelCS_Stock)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 637, Short.MAX_VALUE))
                                    .addGroup(Check_stockLayout.createSequentialGroup()
                                        .addComponent(FieldCS_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_re))))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE))
                        .addGap(23, 23, 23))))
        );
        Check_stockLayout.setVerticalGroup(
            Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Check_stockLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title_checkstock)
                .addGap(18, 18, 18)
                .addGroup(Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Check_stockLayout.createSequentialGroup()
                        .addComponent(LabelCS_Stock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_re))
                    .addGroup(Check_stockLayout.createSequentialGroup()
                        .addGroup(Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCS_ID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCS_Name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Check_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldCS_ID)
                            .addComponent(FieldCS_Name)
                            .addComponent(FieldCS_Stock))))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        Edit_stock.setBackground(new java.awt.Color(204, 204, 204));

        Title_editstock.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Title_editstock.setText("Edit Stock");

        LabelES_Name.setText("Item Name");

        LabelES_Price.setText("Item Price");

        LabelES_Stock.setText("Item Stock");

        BtnES_Update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnES_Update.setText("Update");
        BtnES_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnES_UpdateMouseClicked(evt);
            }
        });

        BtnES_Delete.setBackground(new java.awt.Color(255, 255, 255));
        BtnES_Delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnES_Delete.setForeground(new java.awt.Color(255, 0, 0));
        BtnES_Delete.setText("Delete");
        BtnES_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnES_DeleteMouseClicked(evt);
            }
        });

        jTableES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Name", "Date", "Price[Unit]", "Stock[1=Unit]"
            }
        ));
        jTableES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableESMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableES);

        jComboBoxEs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronics", "Food", "Beauty", "Fashion", "Health", "Household", "Kitchen", "Sports" }));
        jComboBoxEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEsActionPerformed(evt);
            }
        });

        LabelES_Type.setText("Type");

        javax.swing.GroupLayout Edit_stockLayout = new javax.swing.GroupLayout(Edit_stock);
        Edit_stock.setLayout(Edit_stockLayout);
        Edit_stockLayout.setHorizontalGroup(
            Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Edit_stockLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Edit_stockLayout.createSequentialGroup()
                        .addComponent(Title_editstock)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Edit_stockLayout.createSequentialGroup()
                        .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Edit_stockLayout.createSequentialGroup()
                                .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldES_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelES_Name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldES_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelES_Price))
                                .addGap(12, 12, 12)
                                .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelES_Stock)
                                    .addComponent(FieldES_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelES_Type)
                                    .addComponent(jComboBoxEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addComponent(BtnES_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnES_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        Edit_stockLayout.setVerticalGroup(
            Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Edit_stockLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title_editstock)
                .addGap(18, 18, 18)
                .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Edit_stockLayout.createSequentialGroup()
                        .addComponent(LabelES_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldES_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnES_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnES_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Edit_stockLayout.createSequentialGroup()
                        .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelES_Price)
                            .addComponent(LabelES_Stock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Edit_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldES_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldES_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBoxEs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Edit_stockLayout.createSequentialGroup()
                        .addComponent(LabelES_Type)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Edit_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Check_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Edit_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Check_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_checkstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_checkstockMouseClicked
        // TODO add your handling code here:
        Edit_stock.setVisible(false);
        Add_stock.setVisible(false);
        Check_stock.setVisible(true);
        fetchitemDetailsCS();
    }//GEN-LAST:event_Btn_checkstockMouseClicked

    private void Btn_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_AddMouseClicked
        Data user = new Data();
        user.setname(FieldAS_Name.getText());
        user.setprice(FieldAS_Price.getText());
        user.setstock(FieldAS_Stock.getText());
        String type = jComboBoxAs.getSelectedItem().toString();
        
        UserList.add(user);
        
        try{
            String insert = "INSERT INTO Data_item(NAME,TYPE,DATE,PRICE,STOCK) VALUES(?,?,?,?,?)";
            
            pat = con.prepareStatement(insert);
            
            pat.setString(1,user.getname());
            pat.setString(2,type);
            pat.setString(3,user.getdate());
            pat.setString(4,user.getprice());
            pat.setString(5,user.getstock());
            
            pat.execute();
            
            int a = JOptionPane.showConfirmDialog(null, "Please confirm your input: "+"Item name: "+user.getname()+" "
                                                                                                  +"Item type: "+type+" "
                                                                                                  +"Item price: "+user.getprice()+" "
                                                                                                  +"Item stock: "+user.getstock(), "Alert", JOptionPane.INFORMATION_MESSAGE);
            if (a == JOptionPane.YES_OPTION){
                fetchitemDetailsAS();
                }
        }catch (Exception b){
            JOptionPane.showMessageDialog(null, b);
        } 
    }//GEN-LAST:event_Btn_AddMouseClicked

    private void Btn_checkstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_checkstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_checkstockActionPerformed

    private void BtnES_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnES_UpdateMouseClicked
        // TODO add your handling code here:
        int row =jTableES.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTableES.getModel();
        try{
            
            String a = FieldES_Name.getText();
            String b = FieldES_Price.getText();
            String c = FieldES_Stock.getText();
            String d = jComboBoxEs.getSelectedItem().toString();
            String e = model.getValueAt(row, 0).toString();
            System.out.println(jComboBoxEs.getSelectedItem().toString());
            
            String update = "UPDATE Data_item SET TYPE = '"+d+"' , NAME = '"+a+"' , PRICE = '"+b+"', STOCK = '"+c+"'" + "WHERE ID ='"+e+"'";
            
            pat = con.prepareStatement(update);
            
            pat.execute();
            
            JOptionPane.showMessageDialog(null, "Item Updated Successfully");
            fetchitemDetailsES();          
        }catch(Exception b){
            JOptionPane.showMessageDialog(null, b);   
        }
    }//GEN-LAST:event_BtnES_UpdateMouseClicked

    private void Btn_editstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_editstockMouseClicked
        Edit_stock.setVisible(true);
        Add_stock.setVisible(false);
        Check_stock.setVisible(false);
        fetchitemDetailsES();
    }//GEN-LAST:event_Btn_editstockMouseClicked

    private void Btn_addstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_addstockMouseClicked
        Edit_stock.setVisible(false);
        Add_stock.setVisible(true);
        Check_stock.setVisible(false);
        fetchitemDetailsAS();
    }//GEN-LAST:event_Btn_addstockMouseClicked

    private void BtnES_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnES_DeleteMouseClicked
        int row =jTableES.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTableES.getModel();
        
        try{
            String delete = "DELETE FROM Data_item WHERE ID = ?";
            pat = con.prepareStatement(delete);
            pat.setString(1,model.getValueAt(row, 0).toString());
            pat.execute();
            
            int a = JOptionPane.showConfirmDialog(null, "Are you sure to delete this item? : "+model.getValueAt(row, 2).toString(), "Alert", JOptionPane.INFORMATION_MESSAGE);
            if (a == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, "This item has been deleted");
                fetchitemDetailsES();
            }
        }catch(Exception b){
            JOptionPane.showMessageDialog(null, b);
        }    
    }//GEN-LAST:event_BtnES_DeleteMouseClicked

    private void Btn_editstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_editstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_editstockActionPerformed

    private void Btn_addstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_addstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_addstockActionPerformed

    private void jComboBoxAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAsActionPerformed

    private void jComboBoxEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEsActionPerformed

    private void jTableCSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCSMouseClicked
        
    }//GEN-LAST:event_jTableCSMouseClicked

    private void jTableESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableESMouseClicked
        int row =jTableES.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTableES.getModel();
        try{
        FieldES_Name.setText(model.getValueAt(row, 2).toString());
        FieldES_Price.setText(model.getValueAt(row, 4).toString());
        FieldES_Stock.setText(model.getValueAt(row, 5).toString());
        jComboBoxEs.setSelectedItem(model.getValueAt(row, 1).toString());
        }catch(Exception b){
            JOptionPane.showMessageDialog(null, b);
        }
    }//GEN-LAST:event_jTableESMouseClicked

    private void FieldCS_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldCS_IDKeyReleased
        try{
            int i = Integer.parseInt(FieldCS_ID.getText()); 
            String query = "Select * from Data_item where ID like "+i+"";
            pat = con.prepareStatement(query);
            rs = pat.executeQuery();
            jTableCS.setModel(DbUtils.resultSetToTableModel(rs));
            System.out.println(i);
        }catch(Exception b){
        }   
    }//GEN-LAST:event_FieldCS_IDKeyReleased

    private void jTableASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableASMouseClicked
        int row =jTableAS.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTableAS.getModel();
        try{
        FieldAS_Name.setText(model.getValueAt(row, 2).toString());
        FieldAS_Price.setText(model.getValueAt(row, 4).toString());
        FieldAS_Stock.setText(model.getValueAt(row, 5).toString());
        jComboBoxAs.setSelectedItem(model.getValueAt(row, 1).toString());
        }catch(Exception b){
            JOptionPane.showMessageDialog(null, b);
        }
        
    }//GEN-LAST:event_jTableASMouseClicked

    private void FieldCS_StockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldCS_StockKeyReleased
        // TODO add your handling code here:
        try{
            String query = "Select * from Data_item where STOCK like "+FieldCS_Stock.getText()+"";
            pat = con.prepareStatement(query);
            rs = pat.executeQuery();
            jTableCS.setModel(DbUtils.resultSetToTableModel(rs));
            System.out.println(FieldCS_Stock.getText());
        }catch(Exception b){
        }   
    }//GEN-LAST:event_FieldCS_StockKeyReleased

    private void Btn_reMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_reMouseClicked
        // TODO add your handling code here:
        fetchitemDetailsCS();
    }//GEN-LAST:event_Btn_reMouseClicked

    private void FieldCS_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldCS_NameKeyReleased
        // TODO add your handling code here:
        try{
            String query = "Select * from Data_item where NAME like '"+FieldCS_Name.getText().toString()+"'";
            pat = con.prepareStatement(query);
            rs = pat.executeQuery();
            jTableCS.setModel(DbUtils.resultSetToTableModel(rs));
            System.out.println(FieldCS_Name.getText());
        }catch(Exception b){
            System.out.println(b);
        }   
    }//GEN-LAST:event_FieldCS_NameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    
    public void fetchitemDetailsAS(){
        try{
            String view = "SELECT * FROM Data_Item";
            pat = con.prepareStatement(view);
            rs = pat.executeQuery();
            jTableAS.setModel(DbUtils.resultSetToTableModel(rs));  
        }catch(Exception b){
            JOptionPane.showMessageDialog(null, b);
        }
    }
    
    public void fetchitemDetailsES(){
        try{
            String view = "SELECT * FROM Data_Item";
            pat = con.prepareStatement(view);
            rs = pat.executeQuery();  
            jTableES.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception b){
            JOptionPane.showMessageDialog(null, b);
        }
    }
    
    public void fetchitemDetailsCS(){        
        try{
            String view = "SELECT * FROM Data_Item";
            pat = con.prepareStatement(view);  
            rs = pat.executeQuery();
            jTableCS.setModel(DbUtils.resultSetToTableModel(rs)); 
        }catch(Exception b){
            JOptionPane.showMessageDialog(null, b);
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_stock;
    private javax.swing.JButton BtnES_Delete;
    private javax.swing.JButton BtnES_Update;
    private javax.swing.JButton Btn_Add;
    private javax.swing.JButton Btn_addstock;
    private javax.swing.JButton Btn_checkstock;
    private javax.swing.JButton Btn_editstock;
    private javax.swing.JButton Btn_re;
    private javax.swing.JPanel Check_stock;
    private javax.swing.JPanel Edit_stock;
    private javax.swing.JTextField FieldAS_Name;
    private javax.swing.JTextField FieldAS_Price;
    private javax.swing.JTextField FieldAS_Stock;
    private javax.swing.JTextField FieldCS_ID;
    private javax.swing.JTextField FieldCS_Name;
    private javax.swing.JTextField FieldCS_Stock;
    private javax.swing.JTextField FieldES_Name;
    private javax.swing.JTextField FieldES_Price;
    private javax.swing.JTextField FieldES_Stock;
    private javax.swing.JLabel LabelAS_Name;
    private javax.swing.JLabel LabelAS_Price;
    private javax.swing.JLabel LabelAS_Stock;
    private javax.swing.JLabel LabelAS_Type;
    private javax.swing.JLabel LabelCS_ID;
    private javax.swing.JLabel LabelCS_Name;
    private javax.swing.JLabel LabelCS_Stock;
    private javax.swing.JLabel LabelES_Name;
    private javax.swing.JLabel LabelES_Price;
    private javax.swing.JLabel LabelES_Stock;
    private javax.swing.JLabel LabelES_Type;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Menu_bar;
    private javax.swing.JLabel Title_addstrock;
    private javax.swing.JLabel Title_checkstock;
    private javax.swing.JLabel Title_editstock;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxAs;
    private javax.swing.JComboBox<String> jComboBoxEs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTableAS;
    private javax.swing.JTable jTableCS;
    private javax.swing.JTable jTableES;
    // End of variables declaration//GEN-END:variables
}
